import { motion } from "framer-motion";
import { useMemo, useState } from "react";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { blogFilters, blogStories } from "../data/blogs";

const asset = (name: string) => `/assets/${name}`;
export default function Blog() {
  const [filter, setFilter] = useState(blogFilters[0]);
  const [query, setQuery] = useState(new URLSearchParams(window.location.search).get("q") ?? "");
  const stories = useMemo(() => blogStories.filter(s => `${s.title} ${s.category} ${s.summary}`.toLowerCase().includes(query.toLowerCase())), [query]);
  return <div className="min-h-screen bg-[#f8faf9] font-['Plus_Jakarta_Sans:Regular'] text-[#0f1e36]">
    <Navbar />
    <main className="pt-20">
      <section className="px-5 py-16 sm:px-12"><div className="mx-auto max-w-[1280px]">
        <div className="flex flex-col items-start justify-between gap-8 border-b border-[#e4e8e7] pb-6 lg:flex-row lg:items-end"><div><div className="inline-flex items-center gap-2 rounded-full bg-[#d9eaeb] px-3.5 py-1.5 text-[11px] font-bold tracking-[.05em] text-[#005f62]"><i className="size-1.5 rounded-full bg-[#005f62]" />READ BLOGS & BUILD STORIES</div><h1 className="mt-4 font-['Plus_Jakarta_Sans:Bold'] text-[clamp(2.7rem,5vw,3.5rem)] font-bold leading-[1.25] tracking-[-.025em]">Engineering Insights and <span className="font-normal text-[#4d6266]">Build<br />Stories.</span></h1><p className="mt-3 max-w-2xl text-[17px] leading-7 text-[#4d6266]">Detailed technical retrospectives, system design teardowns, hardware prototyping<br className="hidden lg:block" /> logs, and academic viva defense strategies from university engineering teams.</p></div><div className="flex gap-3"><button className="grid size-11 place-items-center rounded-full bg-[#edeeed] text-xl">‹</button><button className="grid size-11 place-items-center rounded-full bg-[#edeeed] text-xl">›</button></div></div>
        <div className="pt-10"><div className="relative"><span className="absolute left-5 top-1/2 -translate-y-1/2 text-xl text-[#4d6266]">⌕</span><input value={query} onChange={e => setQuery(e.target.value)} className="h-[65px] w-full rounded-xl bg-white py-4 pl-12 pr-28 text-[15px] shadow-sm outline-none ring-[#18797d] focus:ring-2" placeholder="Search technical topics, stack, hardware, or university..." /><kbd className="absolute right-3 top-1/2 -translate-y-1/2 rounded-md bg-[#edeeed] px-3 py-1.5 text-[11px] font-bold tracking-widest text-[#4d6266]">⌘ K</kbd></div><div className="mt-5 flex gap-2 overflow-x-auto pb-2">{blogFilters.map(item => <button key={item} onClick={() => setFilter(item)} className={`shrink-0 rounded-full px-4 py-2 text-sm font-semibold shadow-sm transition ${filter === item ? "bg-[#083338] text-white" : "bg-white text-[#4d6266]"}`}>{item}</button>)}</div></div>
      </div></section>
      <section className="px-5 pb-16 sm:px-12"><motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} className="mx-auto grid max-w-[1280px] overflow-hidden rounded-2xl bg-white shadow-lg lg:grid-cols-2"><div className="relative min-h-[360px] overflow-hidden"><img src={asset("fb137.png")} alt="Real-time LiDAR lab workstation" className="absolute inset-0 size-full object-cover" /><div className="absolute left-5 top-5 rounded-xl bg-[#083338]/85 px-3 py-2 text-center text-white backdrop-blur"><b className="block text-3xl leading-7">14</b><span className="text-[11px] font-bold tracking-wider text-[#d9eaeb]">MAR</span></div><span className="absolute right-5 top-5 rounded-full bg-white/95 px-3 py-2 text-xs font-bold">⌖ BUET CSE Capstone</span></div><div className="flex flex-col justify-center p-8 lg:p-10"><div className="flex gap-2 text-xs font-semibold"><span className="rounded-full bg-[#d9eaeb] px-3 py-1.5 text-[#005f62]">Architecture Teardown</span><span className="rounded-full bg-[#edeeed] px-3 py-1.5 text-[#4d6266]">Grade A+ Commendation</span></div><h2 className="mt-5 font-['Plus_Jakarta_Sans:Bold'] text-[clamp(1.8rem,3vw,2.5rem)] font-bold leading-[1.25] tracking-[-.03em]">Building a Real-Time LiDAR SLAM & Point Cloud Pipeline: From PyTorch Prototyping to 18ms Edge Inference.</h2><p className="mt-4 text-[15px] leading-6 text-[#4d6266]">How a senior capstone team tackled sensor fusion drift, memory-mapped zero-copy IPC, and successfully defended with Grade A+ before the external examination committee.</p><div className="mt-6 grid grid-cols-3 border-y border-[#e5e9e8] py-4 text-sm"><div><small>LATENCY</small><b className="block text-lg">18.2 ms</b></div><div><small>MEMORY HEAP</small><b className="block text-lg">340 MB</b></div><div><small>VALIDATION FPS</small><b className="block text-lg text-[#005f62]">54 FPS</b></div></div><div className="mt-5 flex items-center justify-between"><div><b className="text-sm">Engr. Tanvir Ahmed</b><p className="text-xs text-[#4d6266]">BUET '24 • 12 min read • 4.9k views</p></div><button className="rounded-full bg-[#18797d] px-5 py-3 text-sm font-bold text-white">Read Full Build Story →</button></div></div></motion.div></section>
      <section className="bg-[#f2f4f3] px-5 py-16 sm:px-12"><div className="mx-auto max-w-[1280px]"><div className="flex items-end justify-between pb-6"><div><h2 className="text-3xl font-bold tracking-tight">Recent Capstone Retrospectives</h2><p className="mt-2 text-xs font-semibold text-[#4d6266]">Showing {stories.length} of 36 builds</p></div><button className="hidden rounded-lg bg-white px-4 py-2 text-xs font-bold sm:block">Sort: Latest Defense (2026)⌄</button></div><div className="grid gap-6 lg:grid-cols-2">{stories.map((story, index) => <motion.article initial={{ opacity: 0, y: 15 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .04 }} key={story.title} className="flex min-h-[283px] gap-6 rounded-2xl bg-white p-6 shadow-sm"><div className="relative hidden w-[38%] shrink-0 overflow-hidden rounded-xl sm:block"><img src={asset(story.image)} alt="" className="size-full object-cover" /><div className="absolute left-3 top-3 rounded-lg bg-[#083338]/90 px-2 py-1 text-center text-white"><b className="block text-lg leading-4">{story.day}</b><small className="text-[9px]">{story.month}</small></div></div><div className="flex min-w-0 flex-1 flex-col"><div className="text-[11px] font-bold tracking-[.08em] text-[#4d6266]">{story.category}</div><p className="mt-1 truncate text-[13px] text-[#4d6266]">{story.author}</p><h3 className="mt-4 text-[18px] font-bold leading-[1.38] tracking-tight">{story.title}</h3><p className="mt-3 line-clamp-2 text-[13px] leading-5 text-[#4d6266]">{story.summary}</p><div className="mt-auto flex items-center justify-between pt-5"><span className="text-[11px] font-semibold tracking-widest text-[#4d6266]">{story.time}</span><button className="text-sm font-bold text-[#005f62]">Read Story →</button></div></div></motion.article>)}</div><div className="mt-10 flex items-center justify-between"><div className="flex gap-2"><i className="h-1.5 w-10 rounded-full bg-[#18797d]" /><i className="size-1.5 rounded-full bg-[#e1e3e2]" /><i className="size-1.5 rounded-full bg-[#e1e3e2]" /></div><div className="flex gap-2"><button className="grid size-10 place-items-center rounded-full bg-[#18797d] text-white">1</button><button className="grid size-10 place-items-center rounded-full bg-white">2</button><button className="grid size-10 place-items-center rounded-full bg-white">3</button><button className="rounded-full bg-white px-5 text-sm font-semibold">Next →</button></div></div></div></section>
      <section className="px-5 py-16 sm:px-12"><div className="mx-auto grid max-w-[1280px] gap-12 lg:grid-cols-[.85fr_1.15fr]"><div className="self-center"><span className="rounded-full bg-[#fef3c7] px-3 py-1.5 text-[11px] font-bold tracking-wider text-[#d97706]">✦ VIVA READY ARCHITECTURE</span><h2 className="mt-5 text-4xl font-bold leading-tight tracking-tight">How University Project Builder Prepares Your Capstone.</h2><p className="mt-4 leading-6 text-[#4d6266]">Writing code is only 40% of an exemplary engineering submission. We guide university teams through systematic verification, thesis publication standards, and external jury defenses.</p>{["System Architecture Breakdown", "Empirical Benchmark Graphs", "Mock Viva Defense Inquiries"].map((x, i) => <div key={x} className="mt-3 rounded-xl bg-white p-4 shadow-sm"><b className="text-sm">{i + 1}. {x}</b><p className="mt-1 text-[13px] text-[#4d6266]">IEEE-grade engineering detail built for your submission.</p></div>)}</div><div className="rounded-2xl bg-white p-8 shadow-sm"><div className="flex justify-between"><div><b>Capstone Defense Acceptance Rate</b><p className="mt-1 text-xs text-[#4d6266]">Across BUET, DU, IUT, BRACU, and NSU 2024–2025</p></div><span className="rounded-full bg-[#d9eaeb] px-3 py-1 text-[11px] font-bold text-[#005f62]">98.4% FIRST-PASS GRADE A</span></div><div className="mt-8 rounded-xl bg-[#f2f4f3] p-6"><div className="flex h-44 items-end justify-between gap-4">{[42, 58, 76, 91, 98].map((h, i) => <div key={h} className="flex flex-1 flex-col items-center gap-2"><div style={{ height: `${h}%` }} className="w-full rounded-t bg-[#18797d]" /><small className="text-[10px] text-[#4d6266]">S{i + 1}</small></div>)}</div></div></div></div></section>
    </main><Footer />
  </div>;
}
